# Restored constants for RL Engine
ERC_MAP = {
    'Civil': 'CV',
    'Civil Works': 'CV',
    'Civil & Architectural': 'CV',
    'Architectural': 'AR',
    'Mechanical': 'ME',
    'Electrical': 'EL',
    'Plumbing': 'PL',
    'Structure': 'ST',
    'Finishing': 'FN',
    'General': 'GN',
    'Preliminaries': 'PR',
    'Metal Works': 'MW',
    'Wood Works': 'WW',
    'Thermal & Moisture Protection': 'TM',
    'Doors & Windows': 'DW',
    'Special Construction': 'SC',
    'Conveying Systems': 'CS',
    'Fire Suppression': 'FS',
    'HVAC': 'HV',
    'Electrical Power': 'EP',
    'Electronics': 'EC',
    'Earthwork': 'EW',
    'Exterior Improvements': 'EI',
    'Utilities': 'UT',
}
