# Generated by Django 5.2.6 on 2025-11-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0002_project_billitem_project_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='actual_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='actual_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='boq_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='dry_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='labour_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='labour_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='material_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='material_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='material_u_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='material_wastage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='others_1_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='others_1_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='others_1_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='others_2_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='others_2_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='others_2_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='plant_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='plant_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='prelimin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='subcontract_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='subcontract_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='unit_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
