# Generated by Django 5.2.6 on 2025-11-03 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0003_billitem_actual_amount_billitem_actual_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='factor',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200)),
                ('material_rate', models.FloatField(blank=True, null=True)),
                ('material_quantity', models.FloatField(blank=True, null=True)),
                ('material_wastage', models.FloatField(blank=True, default=1.0, null=True)),
                ('material_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('bill_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='excel.billitem')),
            ],
        ),
    ]
