# Generated by Django 5.2.6 on 2025-11-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0004_billitem_factor_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='section_factor',
            field=models.FloatField(default=0.0),
        ),
    ]
