# Generated by Django 5.2.6 on 2025-09-30 07:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DMApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_number', models.CharField(max_length=100, unique=True)),
                ('expiry_date', models.DateField()),
                ('document', models.FileField(blank=True, null=True, upload_to='dm_approvals/')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('lead_time_days', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('uom', models.CharField(max_length=20)),
                ('conversion_factor', models.FloatField(default=1.0)),
                ('standards', models.CharField(blank=True, max_length=255, null=True)),
                ('qc_test_plan_id', models.CharField(max_length=100)),
                ('safety_msds', models.FileField(blank=True, null=True, upload_to='msds/')),
                ('storage_requirements', models.TextField(blank=True, null=True)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('co2_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('reorder_level', models.FloatField(default=0.0)),
                ('reorder_quantity', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dm_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.dmapproval')),
                ('primary_supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='auth_app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='QCResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('test_plan_id', models.CharField(max_length=100)),
                ('outcome', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='MixDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=100)),
                ('dosage', models.FloatField()),
                ('uom', models.CharField(max_length=20)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.FloatField(default=0.0)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='CostElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=100)),
                ('cost_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by', models.CharField(max_length=255)),
                ('qc_reviewed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('final_approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('QC Reviewed', 'QC Reviewed'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Requested', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=100, unique=True)),
                ('order_date', models.DateField()),
                ('expected_delivery', models.DateField()),
                ('quantity', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.rawmaterial')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.supplier')),
            ],
        ),
    ]
